// src/constants.js
export const TEAMS = {
  legal:    { name:'Legal',    icon:'⚖️',  color:'#5b4aaa' },
  projects: { name:'Projects', icon:'🏗️',  color:'#1a5fa8' },
  design:   { name:'Design',   icon:'📐',  color:'#b8860b' },
  vm:       { name:'VM',       icon:'🎨',  color:'#c47d0e' },
  store:    { name:'Store',    icon:'🏪',  color:'#1a7a45' },
  admin:    { name:'Admin',    icon:'👁️',  color:'#b8860b' },
};

export const CATS = {
  licensing:'Licensing', civil:'Civil', hvac:'HVAC', electrical:'Electrical',
  safety:'Safety', facade:'Facade', interior:'Interior', fixtures:'Fixtures',
  design:'Design', media:'Media/Screens', signage:'Signage', it:'IT/POS',
  vm:'VM/Visual', sis:'SIS Brands', store:'Store Ops', milestone:'Milestone',
};

export const STATUS_CFG = {
  not_started: { lbl:'Not Started', color:'#7a7a88', bg:'rgba(90,90,100,0.1)' },
  in_progress:  { lbl:'In Progress', color:'#c47d0e', bg:'rgba(196,125,14,0.1)' },
  done:         { lbl:'Done',        color:'#1a7a45', bg:'rgba(26,122,69,0.1)' },
  blocked:      { lbl:'Blocked',     color:'#c0392b', bg:'rgba(192,57,43,0.1)' },
};

export const PARENT_GROUPS = [
  { id:'grp_legal',    name:'Legal & Licensing',               team:'legal',    category:'licensing', icon:'⚖️',
    children:['l1','l2','l3','l4','l5','l6','l7','l8'] },
  { id:'grp_civil',    name:'Civil & Structural Works',        team:'projects', category:'civil',     icon:'🏗️',
    children:['p1','p2','p5','p14','p18'] },
  { id:'grp_mep',      name:'MEP — Mechanical, Electrical & Plumbing', team:'projects', category:'electrical', icon:'⚡',
    children:['p3','p4','p6','p7','p8','p9','p10','p16'] },
  { id:'grp_facade',   name:'Facade, Signage & Media',         team:'projects', category:'facade',    icon:'🏢',
    children:['p11','p12','p13','p17'] },
  { id:'grp_it',       name:'IT, POS & Systems',               team:'projects', category:'it',        icon:'💻',
    children:['p15'] },
  { id:'grp_fixtures', name:'Fixtures & Design',               team:'design',   category:'fixtures',  icon:'📐',
    children:['des1','des2','des3','des4','des5','fix1','fix2','fix3','fix4','fix5'] },
  { id:'grp_vm',       name:'Visual Merchandising',            team:'vm',       category:'vm',        icon:'🎨',
    children:['vm1','vm2','vm3','vm4','vm5'] },
  { id:'grp_sis',      name:'SIS Brands & Store Setup',        team:'store',    category:'sis',       icon:'🏪',
    children:['st1','st2','st3','st8'] },
  { id:'grp_ops',      name:'Staff & Operations',              team:'store',    category:'store',     icon:'👥',
    children:['st4','st5','st6','st7'] },
];

export const CHILD_TO_PARENT = {};
PARENT_GROUPS.forEach(g => g.children.forEach(c => { CHILD_TO_PARENT[c] = g.id; }));

export const DEFAULT_TASKS = [
  {id:'l1', name:'MCD Trade Licence — Application Filed',           team:'legal',    category:'licensing',  duration:5,  deps:[]},
  {id:'l2', name:'MCD Trade Licence — Approval Received',           team:'legal',    category:'licensing',  duration:45, deps:['l1'], isMilestone:true},
  {id:'l3', name:'Fire NOC — Application + Inspection',             team:'legal',    category:'safety',     duration:30, deps:[]},
  {id:'l4', name:'FSSAI Registration',                              team:'legal',    category:'licensing',  duration:21, deps:[]},
  {id:'l5', name:'Outdoor Signage / Hoarding Permission',           team:'legal',    category:'signage',    duration:14, deps:['l2']},
  {id:'l6', name:'Lift & Escalator Clearance Certificate',          team:'legal',    category:'licensing',  duration:7,  deps:[]},
  {id:'l7', name:'Dedicated Power Connection (500+ KVA)',           team:'legal',    category:'electrical', duration:30, deps:[]},
  {id:'l8', name:'Shop & Establishment Registration',               team:'legal',    category:'licensing',  duration:14, deps:[]},
  {id:'p1', name:'Site Possession / LL Handover',                   team:'projects', category:'civil',      duration:1,  deps:[], isMilestone:true},
  {id:'p2', name:'Demolition & Structural Work',                    team:'projects', category:'civil',      duration:30, deps:['p1']},
  {id:'p3', name:'MEP First Fix (Plumbing + Electrical rough-in)',  team:'projects', category:'electrical', duration:21, deps:['p2']},
  {id:'p4', name:'False Ceiling & Drywall — All Floors',            team:'projects', category:'interior',   duration:14, deps:['p3']},
  {id:'p5', name:'Flooring — All Floors',                           team:'projects', category:'civil',      duration:21, deps:['p2']},
  {id:'p6', name:'Wall Finishes & Painting',                        team:'projects', category:'interior',   duration:14, deps:['p4']},
  {id:'p7', name:'HVAC High Side (ODU Installation)',               team:'projects', category:'hvac',       duration:30, deps:['p2']},
  {id:'p8', name:'HVAC Low Side Ductwork + Commissioning',          team:'projects', category:'hvac',       duration:21, deps:['p7','p4']},
  {id:'p9', name:'LT Panel & Electrical Distribution',              team:'projects', category:'electrical', duration:21, deps:['p3']},
  {id:'p10',name:'Fire Fighting System (Sprinklers + FA)',          team:'projects', category:'safety',     duration:14, deps:['p4']},
  {id:'p11',name:'External Facade & Canopy',                        team:'projects', category:'facade',     duration:21, deps:['p2']},
  {id:'p12',name:'External LED Screens — PO + Production + Install',team:'projects', category:'media',     duration:70, deps:['l2']},
  {id:'p13',name:'Signage Installation (post licence)',             team:'projects', category:'signage',    duration:7,  deps:['l5','p11']},
  {id:'p14',name:'Toilet Fit-Out',                                  team:'projects', category:'interior',   duration:14, deps:['p5']},
  {id:'p15',name:'IT Infrastructure & POS Cabling',                 team:'projects', category:'it',        duration:7,  deps:['p9']},
  {id:'p16',name:'Music System Installation',                       team:'projects', category:'it',        duration:3,  deps:['p9']},
  {id:'p17',name:'Internal LED / TV Screens',                       team:'projects', category:'media',     duration:7,  deps:['p9']},
  {id:'p18',name:'Common Area & Staircase Finishing',               team:'projects', category:'interior',  duration:7,  deps:['p5','p6']},
  {id:'des1',name:'GFC Drawings & Layout Finalised',                team:'design',   category:'design',    duration:7,  deps:['p1'], isMilestone:true},
  {id:'des2',name:'Fixture BOQ Approved + Vendor PO Released',      team:'design',   category:'fixtures',  duration:7,  deps:['des1']},
  {id:'des3',name:'Fixture Production — All Floors',                team:'design',   category:'fixtures',  duration:60, deps:['des2']},
  {id:'fix1',name:'Fixture QC & Dispatch from Factory',             team:'design',   category:'fixtures',  duration:3,  deps:['des3']},
  {id:'fix2',name:'Fixture Delivery to Site',                       team:'design',   category:'fixtures',  duration:2,  deps:['fix1','p5']},
  {id:'fix3',name:'Fixture Installation — GF + FF',                 team:'design',   category:'fixtures',  duration:14, deps:['fix2','p6']},
  {id:'fix4',name:'Fixture Installation — SF + TF',                 team:'design',   category:'fixtures',  duration:14, deps:['fix2','p6']},
  {id:'fix5',name:'Fixture Snagging & Sign-Off',                    team:'design',   category:'fixtures',  duration:5,  deps:['fix3','fix4'], isMilestone:true},
  {id:'des4',name:'Decorative Lighting Install',                    team:'design',   category:'interior',  duration:7,  deps:['fix5']},
  {id:'des5',name:'VM Docket & Category Planograms Finalised',      team:'design',   category:'design',    duration:14, deps:['des1']},
  {id:'vm1', name:'VM Props & Highlight Elements — Procurement',    team:'vm',       category:'vm',        duration:21, deps:['des5']},
  {id:'vm2', name:'Brand Infill Creatives — All Brands Collected',  team:'vm',       category:'vm',        duration:30, deps:['des5']},
  {id:'vm3', name:'Carpets & Soft Furnishings — Order + Deliver',   team:'vm',       category:'vm',        duration:21, deps:['des5']},
  {id:'vm4', name:'Glow Box & Display Creatives Finalised',         team:'vm',       category:'vm',        duration:14, deps:['des5']},
  {id:'vm5', name:'VM Setup & Styling — All Floors',                team:'vm',       category:'vm',        duration:10, deps:['fix5','vm1','vm2','vm3','vm4'], isMilestone:true},
  {id:'st1', name:'SIS Brand Space Allocations Confirmed',          team:'store',    category:'sis',       duration:7,  deps:['des1']},
  {id:'st2', name:'SIS Brand Fixture Designs Approved (FSA)',       team:'store',    category:'sis',       duration:14, deps:['st1']},
  {id:'st3', name:'SIS Fixtures Delivered & Brand Setup Done',      team:'store',    category:'sis',       duration:7,  deps:['st2','fix5']},
  {id:'st4', name:'Staff Hiring Complete',                          team:'store',    category:'store',     duration:45, deps:['p1']},
  {id:'st5', name:'Staff Training & System Onboarding',             team:'store',    category:'store',     duration:10, deps:['st4','p15']},
  {id:'st6', name:'POS Systems Live & Tested',                      team:'store',    category:'it',        duration:3,  deps:['p15','st5']},
  {id:'st7', name:'Merchandise Stock Receiving',                    team:'store',    category:'store',     duration:5,  deps:['vm5','st6']},
  {id:'st8', name:'Bought-Outs & Store Accessories Installed',      team:'store',    category:'store',     duration:3,  deps:['fix5']},
  {id:'LAUNCH',name:'🎯 STORE LAUNCH READY',team:'admin',category:'milestone',duration:0,isMilestone:true,
   deps:['l2','l3','l6','l7','p8','p10','p12','p13','p14','p15','p16','p17','p18','fix5','des4','vm5','st3','st5','st6','st7','st8']},
];
